language: rust
rust:
  - nightly
cache:
  cargo: true
matrix:
  include:
    # https://docs.travis-ci.com/user/reference/osx/#os-x-version
    - os: osx # 10.13
      osx_image: xcode10
    - os: osx # 10.13
      osx_image: xcode9.4
    - os: linux # 14.04
      dist: trusty
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y libdbus-1-dev; fi
before_script:
  - rustup component add clippy-preview rustfmt-preview
script:
  - cargo build
  - cargo test --verbose -- --nocapture
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo fmt --all -- --check
